//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginSdkWizard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PluginSdkWizard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        public static string strAdd {
            get {
                return ResourceManager.GetString("strAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional
        ///preprocessor
        ///definitions.
        /// </summary>
        public static string strAdditionalDefs {
            get {
                return ResourceManager.GetString("strAdditionalDefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional
        ///include
        ///directories.
        /// </summary>
        public static string strAdditionalIncDirs {
            get {
                return ResourceManager.GetString("strAdditionalIncDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional
        ///library
        ///directories.
        /// </summary>
        public static string strAdditionalLibDirs {
            get {
                return ResourceManager.GetString("strAdditionalLibDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional
        ///libraries.
        /// </summary>
        public static string strAdditionalLibs {
            get {
                return ResourceManager.GetString("strAdditionalLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic setup.
        /// </summary>
        public static string strBasicSetup {
            get {
                return ResourceManager.GetString("strBasicSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class name:.
        /// </summary>
        public static string strClassName {
            get {
                return ResourceManager.GetString("strClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug configuration settings.
        /// </summary>
        public static string strDebugConfigurationSettings {
            get {
                return ResourceManager.GetString("strDebugConfigurationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectX 9 SDK.
        /// </summary>
        public static string strDirectX9Sdk {
            get {
                return ResourceManager.GetString("strDirectX9Sdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: Using &apos;{0}&apos; instead of empty path.
        /// </summary>
        public static string strEmptyPathNote {
            get {
                return ResourceManager.GetString("strEmptyPathNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Environment variable &apos;{0}&apos; was not found.
        /// </summary>
        public static string strEnvVarNotFound {
            get {
                return ResourceManager.GetString("strEnvVarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string strFinish {
            get {
                return ResourceManager.GetString("strFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game folder.
        /// </summary>
        public static string strGameFolder {
            get {
                return ResourceManager.GetString("strGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA 3 CLEO SDK.
        /// </summary>
        public static string strIIICleoSdk {
            get {
                return ResourceManager.GetString("strIIICleoSdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA 3 folder.
        /// </summary>
        public static string strIIIGameDir {
            get {
                return ResourceManager.GetString("strIIIGameDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LA compatibility.
        /// </summary>
        public static string strLaCompatibility {
            get {
                return ResourceManager.GetString("strLaCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make plugin compatible with Limit Adjuster.
        /// </summary>
        public static string strLaCompatibilityDescr {
            get {
                return ResourceManager.GetString("strLaCompatibilityDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoonLoader SDK.
        /// </summary>
        public static string strMoonLoaderSdkDir {
            get {
                return ResourceManager.GetString("strMoonLoaderSdkDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoonLoader Module can be created for GTA San Andreas only.
        /// </summary>
        public static string strMoonLoaderWarn1 {
            get {
                return ResourceManager.GetString("strMoonLoaderWarn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoonLoader Module can&apos;t be created for GTA 3.
        /// </summary>
        public static string strMoonLoaderWarn2 {
            get {
                return ResourceManager.GetString("strMoonLoaderWarn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoonLoader Module can&apos;t be created for GTA Vice City.
        /// </summary>
        public static string strMoonLoaderWarn3 {
            get {
                return ResourceManager.GetString("strMoonLoaderWarn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoonLoader Module can&apos;t be created for GTA 3 and GTA Vice City.
        /// </summary>
        public static string strMoonLoaderWarn4 {
            get {
                return ResourceManager.GetString("strMoonLoaderWarn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string strNext {
            get {
                return ResourceManager.GetString("strNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output dir:.
        /// </summary>
        public static string strOutputDir {
            get {
                return ResourceManager.GetString("strOutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin name:.
        /// </summary>
        public static string strPluginName {
            get {
                return ResourceManager.GetString("strPluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugin-sdk folder.
        /// </summary>
        public static string strPluginSdkFolder {
            get {
                return ResourceManager.GetString("strPluginSdkFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin type:.
        /// </summary>
        public static string strPluginType {
            get {
                return ResourceManager.GetString("strPluginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string strPrev {
            get {
                return ResourceManager.GetString("strPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project folder.
        /// </summary>
        public static string strProjectFolder {
            get {
                return ResourceManager.GetString("strProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release configuration settings.
        /// </summary>
        public static string strReleaseConfigurationSettings {
            get {
                return ResourceManager.GetString("strReleaseConfigurationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rwd3d9 folder.
        /// </summary>
        public static string strRwD3d9Folder {
            get {
                return ResourceManager.GetString("strRwD3d9Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA SA cleo plugins.
        /// </summary>
        public static string strSaCleoPlugins {
            get {
                return ResourceManager.GetString("strSaCleoPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA SA CLEO SDK.
        /// </summary>
        public static string strSaCleoSdk {
            get {
                return ResourceManager.GetString("strSaCleoSdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA SA folder.
        /// </summary>
        public static string strSaGameDir {
            get {
                return ResourceManager.GetString("strSaGameDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as Release.
        /// </summary>
        public static string strSameAsRelease {
            get {
                return ResourceManager.GetString("strSameAsRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        public static string strSelectFolder {
            get {
                return ResourceManager.GetString("strSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select game:.
        /// </summary>
        public static string strSelectGame {
            get {
                return ResourceManager.GetString("strSelectGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup paths.
        /// </summary>
        public static string strSetupPaths {
            get {
                return ResourceManager.GetString("strSetupPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test function.
        /// </summary>
        public static string strTestFunction {
            get {
                return ResourceManager.GetString("strTestFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASI Plugin.
        /// </summary>
        public static string strTypeAsi {
            get {
                return ResourceManager.GetString("strTypeAsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEO Plugin.
        /// </summary>
        public static string strTypeCleo {
            get {
                return ResourceManager.GetString("strTypeCleo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLL Library.
        /// </summary>
        public static string strTypeDll {
            get {
                return ResourceManager.GetString("strTypeDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoonLoader Module.
        /// </summary>
        public static string strTypeMoonLoader {
            get {
                return ResourceManager.GetString("strTypeMoonLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use DirectX SDK.
        /// </summary>
        public static string strUseDirectXSdk {
            get {
                return ResourceManager.GetString("strUseDirectXSdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include DirectX SDK headers/libraries.
        /// </summary>
        public static string strUseDirectXSdkDescr {
            get {
                return ResourceManager.GetString("strUseDirectXSdkDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use environment variables.
        /// </summary>
        public static string strUseEnvVars {
            get {
                return ResourceManager.GetString("strUseEnvVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA VC CLEO SDK.
        /// </summary>
        public static string strVcCleoSdk {
            get {
                return ResourceManager.GetString("strVcCleoSdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA VC folder.
        /// </summary>
        public static string strVcGameDir {
            get {
                return ResourceManager.GetString("strVcGameDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string strWarning {
            get {
                return ResourceManager.GetString("strWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Unfinished definition of environment variable: $({0}.
        /// </summary>
        public static string strWarnUnfinishedVar {
            get {
                return ResourceManager.GetString("strWarnUnfinishedVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Plugin-SDK Project Wizard.
        /// </summary>
        public static string strWizardTitle {
            get {
                return ResourceManager.GetString("strWizardTitle", resourceCulture);
            }
        }
    }
}
